steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - jobs
      - deploy
      - code-vs-archframework-job
      - --image=europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest
      - --region=europe-west1
      - --cpu=2
      - --memory=2Gi