steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'


