steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - code-vs-archframework-job
      - --image=europe-docker.pkg.dev/$PROJECT_ID/code-vs-archframework/code-vs-archframework-image:latest
      - --region=europe-west1
      - --platform=managed
      - --memory=12Gi
      - --timeout=999s
      - --concurrency=1
      - --max-instance-count=1
      - --min-instance-count=0
      - --location=europe-west1

